Add full class names as a comment for element and modifier classes in BEM nesting
hudochenkov/ecsstractor pull request #13
Opened 2017-11-23 13:13 UTC by jaakritso

Full class names as comments are especially useful if you're searching for particular classname from the whole directory.

So the searching results are similar to eCSStractor without nesting option.

2017-12-17 19:48 UTC, hudochenkov requested changes
Thank you for your addition! And thank you for your patience waiting for a review.

Could you, please, use CSS comments (`/* comment */`) instead of SCSS comment (`// comment`). Normal comments could be used in many syntaxes (including SCSS), while SCSS comments are very limited.

2017-12-17 19:48 UTC, hudochenkov commented on README.md
> +![ecss_bem_comments](https://raw.githubusercontent.com/jaakritso/ecsstractor/master/eCSStractor-comments.mov.gif)
Replace image code with `![ecss_bem_comments](eCSStractor-comments.mov.gif)`. This way it will link to the image in the correct repository.

2017-12-18 08:47 UTC, jaakritso commented
The need for that kind of comments is necessary only for the nested markup, as the class names are chopped into pieces. In regular CSS it's not possible to write nested CSS anyways ( !? ), so the regular comments are not needed, in my opinion.

But I'll look into it, I'll try to do it so that the default class comments are CSS style, but from the options it's possible to set it as SCSS comments as well.

2017-12-18 09:01 UTC, hudochenkov commented
It also possible to use PostCSS with [postcss-nested](https://github.com/postcss/postcss-nested) plugin. Default PostCSS parser doesn't understand `//` comments.

2018-01-15 13:28 UTC, jaakritso reviewed
Added the default comment style to regular CSS comments and kept the SCSS style comments as a option that is user configurable.

2018-01-16 19:47 UTC, hudochenkov approved these changes

2018-01-16 19:47 UTC, merged

2018-01-16 19:48 UTC, hudochenkov commented
Thanks!

2018-01-16 20:14 UTC, hudochenkov commented
New version `1.8.0` will be available within two hours.